### ISSUE TITLE
Generate a test so "ember test" will fail when there are unused components

### ISSUE THREAD

**Issue by boris-petrov** [vastec/ember-unused-components#12]
Great addon, thanks! I would like my build to fail when there are unused components. So perhaps generate a test (like many other addons do) so that running `ember test` will fail?

**Comment by tniezurawski** [comment]
Sounds good :+1: Although, I think it should be optional.

I'll add it to my TODO list unless you would like to add something like this?

**Comment by boris-petrov** [comment]
Yes, making it optional sounds fine. Please add it to your TODO list, thanks. :)

**Comment by tniezurawski** [comment]
@boris-petrov [We went a bit different path](https://github.com/vastec/ember-unused-components/pull/31) but I believe "the problem" was the same :)
So the solution is to use `failOnUnused` option and configure CI to fail if unused components were found.

Here are the details on how to use it: https://github.com/vastec/ember-unused-components#fail-on-unused

**Comment by tniezurawski** [comment]
Released with `1.1.0` version.

**Comment by jbryson3** [comment]
Sorry to bump an old thread, but I'd like to second the opinion that it would be great to have a failing unit test if there are unused components. That way, I wouldn't have to change my CI commands at all - I already run unit tests.
