### ISSUE TITLE
Does not find template-only components

### ISSUE THREAD

**Issue by boris-petrov** [vastec/ember-unused-components#18]
The function `mapComponents` in `lib/analyzer.js` is called only with `app/components` which means that components that only have a template won't be indexed. So the same `mapComponents` function should also be called with `app/templates/components` I guess.

**Comment by maxwondercorn** [comment]
Another case of template only components is in `ember-light-table`.  A custom component for the header icons is only specified in the template.  Specifically with `iconComponent` in the table head declaration.  There may be others.

Thanks for adding the search for components only used in ELT javascript files.

**Comment by jkeen** [comment]
@maxwondercorn I believe this issue has been resolved in the latest release (1.2.0), which includes a major change to how the files were being indexed and categorized. I just tested this on a project and some template only components come up for me

**Comment by boris-petrov** [comment]
Closing then! Thanks!
