### ISSUE TITLE
Better component matching

### ISSUE THREAD

**Issue by ctjhoa** [vastec/ember-unused-components#3]
Hi I just discover your repository while trying to write similar addon and it's a great discovery!

You can find my experimental addon [here](https://github.com/concordnow/ember-graveyard)
I took a different approach I've written all the main part in a [bash script](https://github.com/concordnow/ember-graveyard/blob/master/dead_components.sh) (I don't care about OS compatibility for the moment).

I've discover that your addon miss some cases like inheritance, for example.
```js
// components/concrete.js
import AbstractComponent from 'my-app/components/abstract';

export default AbstractComponent.extend({
   // do stuff
})
```

or some addons like [ember-light-table](https://github.com/offirgolan/ember-light-table) declare stuff like:
```js
// components/my-table.js
import { computed } from '@ember/object';
import Table from 'ember-light-table';

export default Ember.Component.extend({
  model: null,

  columns: computed(function() {
    return [{
      label: 'Avatar',
      valuePath: 'avatar',
      width: '60px',
      sortable: false,
      cellComponent: 'user-avatar' // <----- here is the issue
    }];
  }),

  table: computed('model', function() {
   return new Table(this.get('columns'), this.get('model'));
  })
});
```

So I made a PR to fix that -> #2

**Comment by ctjhoa** [comment]
I've also notice that you don't provide any cleanup option to directly remove components from the addon.
Something like `ember unused:components --cleanup`. 

I have achieved this in my project with [dirty exec](https://github.com/concordnow/ember-graveyard/blob/master/index.js#L25)
Do you know a way to call directly another ember command without spawning another process?

**Comment by tniezurawski** [comment]
Hi @ctjhoa,
sorry for a very very long delay.
You've made awesome work reporting all the issues and creating Pull Requests! Big thank you!

In fact, I was thinking about rewriting this addon into a bash script or pure npm package :D It seems like an addon might be too much here. What do you think about that?

I know there are many cases where this addon is not working properly but TBH I don't have much time to improve it or even test proposed changes.

**Comment by ctjhoa** [comment]
#2 fix the two issues so I close this ticket
