### ISSUE TITLE
Cleanup option

### ISSUE THREAD

**Issue by ctjhoa** [vastec/ember-unused-components#4]
I've also notice that you don't provide any cleanup option to directly remove components from the addon.
Something like `ember unused:components --cleanup`. 

I have achieved this in my project with [dirty exec](https://github.com/concordnow/ember-graveyard/blob/master/index.js#L25)
Do you know a way to call directly another ember command without spawning another process?

**Comment by tniezurawski** [comment]
To be honest I do not plan to implement this feature as stated in [README.md - Removing components](https://github.com/vastec/ember-unused-components#removing-components).

That would be risky and it's super easy to omit files or dependencies related to a component. I'd like to encourage people to eliminate dead code and do some thinking process around removing a component.
