### ISSUE TITLE
Octane Support?

### ISSUE THREAD

**Issue by NullVoxPopuli** [vastec/ember-unused-components#8]
I don't have an app directory :(
```bash
$ ember unused:components
Searching for unused components:
ENOENT: no such file or directory, scandir './app/components'
```

**Comment by tniezurawski** [comment]
@NullVoxPopuli I've just released version `1.0.0` that supports Module Unification which you were probably referring too. [It's no longer a part of Octane though](https://blog.emberjs.com/2019/03/11/update-on-module-unification-and-octane.html).

**Comment by NullVoxPopuli** [comment]
awesome, thanks! 

I'm aware that MU is no longer a part of octane, but I'm still usin it :)

It also isn't going to be the final version of the new layout. :man_shrugging: :smile:

**Comment by tniezurawski** [comment]
> It also isn't going to be the final version of the new layout.

Yeah. That's a tricky part for this script :D But I'll try to follow ;)
