### ISSUE TITLE
Support for Angle Bracket Components

### ISSUE THREAD

**Issue by topbloc-beiswenger** [vastec/ember-unused-components#9]
Since version 3.7, Ember [supports angle bracket components](https://github.com/emberjs/ember.js/blob/master/CHANGELOG.md#v340-august-27-2018). When running this addon, it does not recognize the usage of angle bracket components.

**Comment by tniezurawski** [comment]
@topbloc-beiswenger I've just released version `1.0.0` that supports angle bracket components (nested too).
